from _typeshed import Incomplete
from cat.agents import AgentOutput, BaseAgent
from cat.experimental.form import CatForm as CatForm
from cat.looking_glass.output_parser import LLMAction as LLMAction
from cat.mad_hatter.decorators.tool import CatTool as CatTool

class ProceduresAgent(BaseAgent):
    form_agent: Incomplete
    allowed_procedures: dict[str, CatTool | CatForm]
    def execute(self, stray) -> AgentOutput: ...
    def execute_procedures(self, stray): ...
    def execute_chain(self, stray, procedures_prompt_template, allowed_procedures) -> LLMAction: ...
    def execute_subagents(self, stray, llm_action, allowed_procedures): ...
    def get_recalled_procedures_names(self, stray) -> set: ...
    def prepare_allowed_procedures(self, stray, recalled_procedures_names) -> dict[str, CatTool | CatForm]: ...
    def generate_examples(self, allowed_procedures): ...
